# Generated by Django 2.1.5 on 2021-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='video',
            field=models.CharField(max_length=300, null='true'),
            preserve_default='true',
        ),
    ]
